import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import './styles.css';

const socket = io(import.meta.env.VITE_SERVER_URL || 'http://localhost:3001', { autoConnect: true });
const request = (event, payload) => new Promise(resolve => socket.emit(event, payload, resolve));
const initial = { mode: null, roomCode: '', state: null, question: null, result: null, report: null, selected: null, submitted: false, progress: null, error: '' };

function App() {
  const [app, setApp] = useState(initial);
  const [name, setName] = useState('');
  const [joinCode, setJoinCode] = useState('');
  const [connected, setConnected] = useState(socket.connected);
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const onConnect = () => setConnected(true); const onDisconnect = () => setConnected(false); const onState = state => setApp(a => ({ ...a, state, roomCode: state.roomCode })); const onQuestion = question => setApp(a => ({ ...a, question, selected: null, submitted: false, error: '' })); const onAccepted = () => setApp(a => ({ ...a, submitted: true })); const onProgress = progress => setApp(a => ({ ...a, progress })); const onFinished = () => setApp(a => ({ ...a, state: a.state && { ...a.state, status: 'FINISHED' }, question: null })); const onResult = result => setApp(a => ({ ...a, result })); const onReport = report => setApp(a => ({ ...a, report })); const onSnapshot = snapshot => setApp(a => ({ ...a, state: snapshot.state, question: snapshot.question, submitted: Boolean(snapshot.hasAnsweredCurrentQuestion), roomCode: snapshot.state.roomCode })); const onError = error => setApp(a => ({ ...a, error: error.message })); socket.on('connect', onConnect); socket.on('disconnect', onDisconnect); socket.on('room:state', onState); socket.on('question:changed', onQuestion); socket.on('answer:accepted', onAccepted); socket.on('answer:progress', onProgress); socket.on('quiz:finished', onFinished); socket.on('player:result', onResult); socket.on('quiz:report', onReport); socket.on('room:snapshot', onSnapshot); socket.on('error', onError); return () => ['connect','disconnect','room:state','question:changed','answer:accepted','answer:progress','quiz:finished','player:result','quiz:report','room:snapshot','error'].forEach(event => socket.off(event)); }, []);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(timer); }, []);
  const secondsLeft = useMemo(() => app.question ? Math.max(0, Math.ceil((app.question.durationSeconds * 1000 - (now - (app.state?.questionStartedAt || now))) / 1000)) : 0, [app.question, app.state, now]);
  const message = app.error && <div className="alert">{app.error}</div>;
  if (!app.mode) return <Landing connected={connected} name={name} setName={setName} joinCode={joinCode} setJoinCode={setJoinCode} onHost={async () => { const res = await request('room:create', { hostName: name || 'Host' }); if (res.success) setApp(a => ({ ...a, mode: 'host', roomCode: res.roomCode, state: res.state })); else setApp(a => ({ ...a, error: res.message })); }} onJoin={async () => { const res = await request('room:join', { roomCode: joinCode, nickname: name }); if (res.success) setApp(a => ({ ...a, mode: 'player', roomCode: joinCode.toUpperCase(), state: res.state })); else setApp(a => ({ ...a, error: res.message })); }} />;
  if (app.state?.status === 'FINISHED' || app.result || app.report) return <Result app={app} onReset={() => setApp(initial)} />;
  if (app.mode === 'host') return <Host app={app} secondsLeft={secondsLeft} message={message} onStart={async () => { const res = await request('quiz:start', { roomCode: app.roomCode }); if (!res.success) setApp(a => ({ ...a, error: res.message })); }} onNext={async () => { const res = await request('question:next', { roomCode: app.roomCode }); if (!res.success) setApp(a => ({ ...a, error: res.message })); }} onFinish={async () => { const res = await request('quiz:finish', { roomCode: app.roomCode }); if (!res.success) setApp(a => ({ ...a, error: res.message })); }} />;
  return <Player app={app} secondsLeft={secondsLeft} message={message} onSelect={selected => setApp(a => ({ ...a, selected }))} onSubmit={async () => { const res = await request('answer:submit', { roomCode: app.roomCode, questionId: app.question.id, selectedOptionId: app.selected }); if (!res.success) setApp(a => ({ ...a, error: res.message })); }} onSync={() => socket.emit('room:sync', { roomCode: app.roomCode })} />;
}

function Shell({ children, connected }) { return <main><div className="topbar"><div className="brand"><span className="logo">Q</span><span>QForge <small>REALTIME POC</small></span></div><span className={`connection ${connected ? 'online' : ''}`}>{connected ? 'Connected' : 'Disconnected'}</span></div>{children}</main>; }
function Landing({ connected, name, setName, joinCode, setJoinCode, onHost, onJoin }) { return <Shell connected={connected}><section className="hero"><p className="eyebrow">REALTIME QUIZ LAB</p><h1>Make every answer<br /><em>count.</em></h1><p className="sub">A tiny, fast demo of live quiz synchronization with Socket.IO.</p><div className="card launch"><label>Your nickname<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Alex" /></label><div className="split"><button onClick={onHost}>Create room <span>→</span></button><div className="join"><input value={joinCode} onChange={e => setJoinCode(e.target.value.toUpperCase())} placeholder="ROOM PIN" maxLength={6} /><button className="secondary" onClick={onJoin}>Join</button></div></div></div></section></Shell>; }
function Host({ app, secondsLeft, message, onStart, onNext, onFinish }) { const active = app.state?.status === 'ACTIVE'; return <Shell connected><section className="workspace"><div className="workspace-head"><div><p className="eyebrow">HOST CONTROL ROOM</p><h2>Room <strong>{app.roomCode}</strong></h2></div><span className={`pill ${active ? 'active' : ''}`}>{active ? 'LIVE' : 'WAITING'}</span></div>{message}<div className="grid"><div className="card main-card">{active && app.question ? <QuestionPreview question={app.question} secondsLeft={secondsLeft} /> : <div className="empty"><div className="big-pin">{app.roomCode}</div><h3>Ready when you are.</h3><p>Share this room PIN with your players.</p></div>}{active && <div className="controls"><button className="secondary" onClick={onNext}>Next question →</button><button className="danger" onClick={onFinish}>Finish quiz</button></div>}{!active && <button onClick={onStart} disabled={!app.state?.players?.length}>Start quiz <span>→</span></button>}</div><aside className="card sidebar"><div className="side-title"><h3>Players</h3><span className="count">{app.state?.players?.length || 0}</span></div>{app.state?.players?.length ? app.state.players.map(p => <div className="player" key={p.id}><span className="avatar">{p.nickname[0]?.toUpperCase()}</span>{p.nickname}<span className="dot" /></div>) : <p className="muted">Waiting for players to join...</p>}{active && <div className="progress"><span>Answer progress</span><b>{app.progress?.answered || 0} / {app.progress?.total || app.state.players.length}</b></div>}</aside></div></section></Shell>; }
function QuestionPreview({ question, secondsLeft }) { return <div className="question-preview"><div className="question-meta"><span>Question {question.index + 1} of {question.totalQuestions}</span><b className={secondsLeft <= 3 ? 'urgent' : ''}>{secondsLeft}s</b></div><h3>{question.text}</h3><div className="options">{question.options.map((option, index) => <div className="option" key={option.id}><span>{String.fromCharCode(65 + index)}</span>{option.text}</div>)}</div></div>; }
function Player({ app, secondsLeft, message, onSelect, onSubmit, onSync }) { return <Shell connected><section className="workspace player-view"><div className="workspace-head"><div><p className="eyebrow">LIVE QUIZ · ROOM {app.roomCode}</p><h2>{app.state?.status === 'WAITING' ? 'You are in.' : 'Your turn.'}</h2></div><button className="link-button" onClick={onSync}>Sync state ↻</button></div>{message}{app.state?.status === 'WAITING' && <div className="card waiting"><div className="loader">•••</div><h3>Waiting for the host to start</h3><p>Stay on this screen. Your question will appear here.</p><div className="waiting-players">{app.state.players?.length || 0} players in the room</div></div>}{app.question && <div className="card player-question"><div className="question-meta"><span>Question {app.question.index + 1} of {app.question.totalQuestions}</span><b className={secondsLeft <= 3 ? 'urgent' : ''}>{secondsLeft}s</b></div><h3>{app.question.text}</h3><div className="answer-options">{app.question.options.map((option, index) => <button disabled={app.submitted || secondsLeft === 0} className={app.selected === option.id ? 'selected' : ''} onClick={() => onSelect(option.id)} key={option.id}><span>{String.fromCharCode(65 + index)}</span>{option.text}</button>)}</div><button onClick={onSubmit} disabled={!app.selected || app.submitted || secondsLeft === 0}>{app.submitted ? 'Answer submitted ✓' : 'Submit answer →'}</button></div>}</section></Shell>; }
function Result({ app, onReset }) { const own = app.result; const rows = app.report?.participants || (own ? [own] : []); return <Shell connected><section className="workspace result-view"><p className="eyebrow">QUIZ COMPLETE</p><h2>Nice work.</h2>{own && <div className="score-card"><span>Your score</span><strong>{own.score}</strong><p>{own.correct} correct · {own.accuracy}% accuracy</p></div>}<div className="card report"><div className="side-title"><h3>{app.report ? 'Session report' : 'Your result'}</h3><span className="count">{rows.length}</span></div>{rows.map((row, index) => <div className="result-row" key={row.playerId}><span className="rank">{index + 1}</span><b>{row.nickname}</b><span>{row.correct} correct</span><strong>{row.score}</strong></div>)}</div><button onClick={onReset}>Back to start</button></section></Shell>; }
createRoot(document.getElementById('root')).render(<App />);
